version: '3'
services:
  gcfrontend:
    build: .
    restart: always
    networks:
    - web
    - default
    expose:
    - "80"
    labels:
    - "traefik.docker.network=web"
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:gcmedia.mrtg.stream"
    - "traefik.backend=gcfrontend"
    - "traefik.port=80"
    - "traefik.protocol=http"
networks:
  web:
    external: true